services:
  tasks-api:
    image: test-tasks-api
    build:
      context: .
      target: test
    command: pytest
    environment:
      SQLITE_FILENAME: "test.db"
    volumes:
      - "./src:/app/src"
      - "./tests:/app/tests"
      - "./data:/app/data"
